import type { RawJob } from "../../lib/types";
import type { SourceAdapter } from "./types";

// Curated baseline. Always on, so the site is never empty and 国内大厂/金融/快消
// always have entries even when live crawlers return little. Links point at the
// company's official campus/careers page (stable). Keep deadlines in the future
// relative to the current recruiting season; expired rows are auto-dropped.

export const SEED_JOBS: RawJob[] = [
  // ───────────────────────── 互联网 / 科技大厂 ─────────────────────────
  { origin: "seed", company: "字节跳动", companyTier: 1, title: "2027 暑期实习 · 技术/产品/运营", category: "互联网", jobType: "暑期实习", location: ["北京", "上海", "杭州", "深圳"], salary: "300-600/天", requirements: "本科及以上", deadline: "2026-10-31", description: "覆盖抖音、TikTok、飞书、火山引擎等核心业务，表现优异可拿转正 offer。", applyUrl: "https://jobs.bytedance.com/campus", tags: ["大厂", "转正机会"] },
  { origin: "seed", company: "腾讯", companyTier: 1, title: "2026 秋季校园招聘", category: "互联网", jobType: "秋招", location: ["深圳", "北京", "上海"], requirements: "应届毕业生", deadline: "2026-09-20", description: "技术/产品/设计/市场多通道，微信、游戏、云与智慧产业等事业群。", applyUrl: "https://join.qq.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "阿里巴巴", companyTier: 1, title: "2026 秋招 · 技术线", category: "互联网", jobType: "秋招", location: ["杭州", "北京"], requirements: "应届毕业生", deadline: "2026-09-30", description: "淘天集团 / 阿里云 / 国际数字商业，研发、算法、数据多岗位。", applyUrl: "https://talent.alibaba.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "美团", companyTier: 1, title: "2026 秋季校园招聘", category: "互联网", jobType: "秋招", location: ["北京", "上海"], requirements: "应届毕业生", deadline: "2026-09-15", description: "到店、到家、基础研发平台等方向，技术与产品岗位。", applyUrl: "https://campus.meituan.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "百度", companyTier: 1, title: "2027 AI 暑期实习", category: "互联网", jobType: "暑期实习", location: ["北京"], salary: "300-500/天", requirements: "本科及以上", deadline: "2026-11-30", description: "文心大模型、Apollo 自动驾驶、智能云方向算法与工程实习。", applyUrl: "https://talent.baidu.com/", tags: ["大厂", "AI"] },
  { origin: "seed", company: "快手", companyTier: 1, title: "2026 秋季校园招聘", category: "互联网", jobType: "秋招", location: ["北京"], requirements: "应届毕业生", deadline: "2026-09-10", description: "算法、工程、产品、商业化多岗位。", applyUrl: "https://campus.kuaishou.cn/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "京东", companyTier: 1, title: "2026 秋招", category: "互联网", jobType: "秋招", location: ["北京", "宿迁"], requirements: "应届毕业生", deadline: "2026-09-25", description: "零售、物流、科技、健康多业务线技术与管培岗位。", applyUrl: "https://campus.jd.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "拼多多", companyTier: 1, title: "2026 秋招", category: "互联网", jobType: "秋招", location: ["上海"], requirements: "应届毕业生", deadline: "2026-08-31", description: "多多电商、Temu 国际化方向研发与算法岗位。", applyUrl: "https://careers.pinduoduo.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "网易", companyTier: 1, title: "2026 秋招", category: "互联网", jobType: "秋招", location: ["杭州", "广州"], requirements: "应届毕业生", deadline: "2026-09-18", description: "游戏、有道、云音乐、严选等事业部。", applyUrl: "https://campus.163.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "滴滴", companyTier: 1, title: "日常实习 · 研发/算法", category: "互联网", jobType: "日常实习", location: ["北京"], salary: "200-400/天", requirements: "在校生", deadline: null, description: "网约车、地图、国际化业务长期实习，滚动招聘。", applyUrl: "https://campus.didiglobal.com/", tags: ["大厂", "长期实习"] },
  { origin: "seed", company: "小红书", companyTier: 1, title: "2027 暑期实习", category: "互联网", jobType: "暑期实习", location: ["上海", "北京"], salary: "300-500/天", requirements: "本科及以上", deadline: "2026-11-15", description: "社区、电商、算法、商业化多方向。", applyUrl: "https://job.xiaohongshu.com/", tags: ["大厂", "转正机会"] },
  { origin: "seed", company: "哔哩哔哩", companyTier: 2, title: "2026 秋招", category: "互联网", jobType: "秋招", location: ["上海"], requirements: "应届毕业生", deadline: "2026-09-12", description: "技术、产品、运营、内容多岗位。", applyUrl: "https://jobs.bilibili.com/campus", tags: ["校招"] },
  { origin: "seed", company: "蚂蚁集团", companyTier: 1, title: "2026 秋招 · 技术", category: "互联网", jobType: "秋招", location: ["杭州", "上海"], requirements: "应届毕业生", deadline: "2026-09-22", description: "支付宝、数字金融、隐私计算与大模型方向。", applyUrl: "https://talent.antgroup.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "携程", companyTier: 2, title: "日常实习 · 多岗位", category: "互联网", jobType: "日常实习", location: ["上海"], salary: "150-300/天", requirements: "在校生", deadline: null, description: "旅游平台技术、产品、数据分析长期实习。", applyUrl: "https://careers.ctrip.com/", tags: ["长期实习"] },
  { origin: "seed", company: "小米", companyTier: 1, title: "2026 秋季校园招聘", category: "互联网", jobType: "秋招", location: ["北京", "武汉", "南京"], requirements: "应届毕业生", deadline: "2026-09-28", description: "手机、汽车、IoT、互联网多业务线。", applyUrl: "https://hr.xiaomi.com/", tags: ["大厂", "校招"] },

  // ───────────────────────── 金融 ─────────────────────────
  { origin: "seed", company: "中金公司", companyTier: 1, title: "2027 暑期实习", category: "金融", jobType: "暑期实习", location: ["北京", "上海"], salary: "200-300/天", requirements: "硕士及以上", deadline: "2026-12-15", description: "投资银行部、研究部、固定收益部等暑期实习项目。", applyUrl: "https://www.cicc.com/", tags: ["头部券商", "Top投行"] },
  { origin: "seed", company: "中信证券", companyTier: 1, title: "2026 秋季校园招聘", category: "金融", jobType: "秋招", location: ["北京", "深圳"], requirements: "硕士及以上", deadline: "2026-09-30", description: "国内龙头券商，投行、研究、资管多条线。", applyUrl: "https://www.citics.com/", tags: ["头部券商", "校招"] },
  { origin: "seed", company: "高盛", companyTier: 1, title: "2027 Summer Analyst", category: "金融", jobType: "暑期实习", location: ["北京", "上海"], region: "大陆", salary: "10000+/月", requirements: "在校大学生", deadline: "2026-10-15", description: "全球顶级投行暑期项目，表现优异可获全职 offer。", applyUrl: "https://www.goldmansachs.com/careers/students-and-graduates/", tags: ["外资", "Top投行"] },
  { origin: "seed", company: "摩根大通", companyTier: 1, title: "2027 Summer Analyst", category: "金融", jobType: "暑期实习", location: ["上海"], region: "大陆", salary: "10000+/月", requirements: "本科及以上", deadline: "2026-10-01", description: "J.P. Morgan 全球暑期项目，投行/市场/资管方向。", applyUrl: "https://careers.jpmorgan.com/global/en/students", tags: ["外资", "Top投行"] },
  { origin: "seed", company: "摩根士丹利", companyTier: 1, title: "2027 暑期实习", category: "金融", jobType: "暑期实习", location: ["上海"], region: "大陆", requirements: "本科及以上", deadline: "2026-10-20", description: "Morgan Stanley 暑期分析师项目。", applyUrl: "https://www.morganstanley.com/people-opportunities/students-graduates", tags: ["外资", "Top投行"] },
  { origin: "seed", company: "汇丰银行", companyTier: 2, title: "2026 环球银行暑期实习", category: "金融", jobType: "暑期实习", location: ["上海", "广州"], requirements: "本科及以上", deadline: "2026-09-30", description: "HSBC 商业银行、环球银行与市场方向。", applyUrl: "https://www.hsbc.com/careers/students-and-graduates", tags: ["外资"] },
  { origin: "seed", company: "安永", companyTier: 2, title: "2026 暑期实习", category: "金融", jobType: "暑期实习", location: ["北京", "上海", "广州", "深圳"], salary: "100-200/天", requirements: "本科及以上", deadline: "2026-08-31", description: "审计、税务、咨询暑期实习，有转正机会。", applyUrl: "https://www.ey.com/zh_cn/careers", tags: ["四大"] },
  { origin: "seed", company: "普华永道", companyTier: 2, title: "2026 精英计划暑期实习", category: "金融", jobType: "暑期实习", location: ["上海", "北京"], salary: "100-200/天", requirements: "本科及以上", deadline: "2026-08-20", description: "PwC 审计与咨询暑期实习。", applyUrl: "https://www.pwccn.com/zh/careers.html", tags: ["四大"] },
  { origin: "seed", company: "德勤", companyTier: 2, title: "2026 秋季校园招聘", category: "金融", jobType: "秋招", location: ["北京", "上海", "广州", "深圳"], requirements: "应届毕业生", deadline: "2026-09-15", description: "Deloitte 审计、咨询、税务、风险全条线。", applyUrl: "https://www2.deloitte.com/cn/zh/careers.html", tags: ["四大", "校招"] },
  { origin: "seed", company: "毕马威", companyTier: 2, title: "2026 秋季校园招聘", category: "金融", jobType: "秋招", location: ["北京", "上海"], requirements: "应届毕业生", deadline: "2026-09-10", description: "KPMG 审计、税务、咨询方向。", applyUrl: "https://kpmg.com/cn/zh/home/careers.html", tags: ["四大", "校招"] },
  { origin: "seed", company: "华泰证券", companyTier: 2, title: "2026 秋招", category: "金融", jobType: "秋招", location: ["南京", "上海"], requirements: "硕士及以上", deadline: "2026-09-25", description: "财富管理、投行、研究所多岗位。", applyUrl: "https://www.htsc.com.cn/", tags: ["头部券商", "校招"] },
  { origin: "seed", company: "招商银行", companyTier: 2, title: "2026 秋招 · 管培方向", category: "金融", jobType: "秋招", location: ["深圳"], requirements: "应届毕业生", deadline: "2026-09-30", description: "总行管培、金融科技、风险管理多方向。", applyUrl: "http://career.cmbchina.com/", tags: ["银行", "管培"] },

  // ───────────────────────── 外企 & 海外科技 ─────────────────────────
  { origin: "seed", company: "微软", companyTier: 1, title: "2027 暑期实习", category: "外企", jobType: "暑期实习", location: ["北京", "上海", "苏州"], region: "大陆", requirements: "本科及以上", deadline: "2026-11-30", description: "Microsoft 研发实习，Azure、Office、AI 等方向。", applyUrl: "https://careers.microsoft.com/v2/global/en/students.html", tags: ["外企", "科技"] },
  { origin: "seed", company: "谷歌", companyTier: 1, title: "2027 Internship (APAC)", category: "外企", jobType: "暑期实习", location: ["新加坡", "海外"], region: "海外", requirements: "本科及以上", deadline: "2026-10-31", description: "Google 软件工程暑期实习（亚太/海外）。", applyUrl: "https://careers.google.com/students/", tags: ["外企", "海外"] },
  { origin: "seed", company: "亚马逊", companyTier: 1, title: "2026 SDE Intern", category: "外企", jobType: "暑期实习", location: ["新加坡", "海外"], region: "海外", requirements: "本科及以上", deadline: "2026-09-30", description: "Amazon 软件开发实习，全球团队。", applyUrl: "https://www.amazon.jobs/content/en/career-programs/university", tags: ["外企", "海外"] },
  { origin: "seed", company: "英伟达", companyTier: 1, title: "2027 暑期实习", category: "外企", jobType: "暑期实习", location: ["上海", "北京", "海外"], requirements: "本科及以上", deadline: "2026-11-15", description: "NVIDIA 深度学习、芯片、系统软件方向。", applyUrl: "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/", tags: ["外企", "AI", "芯片"] },
  { origin: "seed", company: "Meta", companyTier: 1, title: "2027 University Internship", category: "外企", jobType: "暑期实习", location: ["海外"], region: "海外", requirements: "本科及以上", deadline: "2026-10-15", description: "Meta 软件工程与研究实习（海外）。", applyUrl: "https://www.metacareers.com/careerprograms/students/", tags: ["外企", "海外"] },
  { origin: "seed", company: "苹果", companyTier: 1, title: "2026 校园招聘", category: "外企", jobType: "校招", location: ["上海", "北京", "深圳"], region: "大陆", requirements: "应届毕业生", deadline: "2026-09-30", description: "Apple 硬件、软件、供应链多方向。", applyUrl: "https://www.apple.com.cn/careers/cn/", tags: ["外企", "科技"] },
  { origin: "seed", company: "SAP", companyTier: 2, title: "2026 暑期实习", category: "外企", jobType: "暑期实习", location: ["上海"], region: "大陆", requirements: "本科及以上", deadline: "2026-08-31", description: "企业软件研发与解决方案实习。", applyUrl: "https://jobs.sap.com/", tags: ["外企"] },
  { origin: "seed", company: "埃森哲", companyTier: 2, title: "2026 秋季校园招聘", category: "外企", jobType: "秋招", location: ["上海", "北京", "大连"], region: "大陆", requirements: "应届毕业生", deadline: "2026-09-25", description: "Accenture 咨询、技术与数字化方向。", applyUrl: "https://www.accenture.cn/cn-zh/careers", tags: ["外企", "咨询"] },

  // ───────────────────────── 快消 / 管培 ─────────────────────────
  { origin: "seed", company: "宝洁", companyTier: 1, title: "2026 暑期实习", category: "快消", jobType: "暑期实习", location: ["广州", "上海", "北京"], salary: "350-450/天", requirements: "本科及以上", deadline: "2026-08-15", description: "P&G CBD、品牌、研发、供应链暑期实习。", applyUrl: "https://www.pgcareers.com/", tags: ["外企", "快消"] },
  { origin: "seed", company: "联合利华", companyTier: 1, title: "2026 UFLP 暑期实习", category: "管培", jobType: "暑期实习", location: ["上海"], salary: "300-400/天", requirements: "本科及以上", deadline: "2026-08-20", description: "Unilever 未来领袖计划暑期实习，转正进入管培。", applyUrl: "https://careers.unilever.com/", tags: ["外企", "管培"] },
  { origin: "seed", company: "欧莱雅", companyTier: 2, title: "2026 暑期实习", category: "快消", jobType: "暑期实习", location: ["上海", "北京"], salary: "300/天", requirements: "本科及以上", deadline: "2026-08-31", description: "L'Oréal 市场、电商、研发暑期实习。", applyUrl: "https://www.loreal.com/en/careers/", tags: ["外企", "快消"] },
  { origin: "seed", company: "玛氏", companyTier: 2, title: "2026 MLDP 管培生", category: "管培", jobType: "校招", location: ["上海", "广州"], requirements: "应届毕业生", deadline: "2026-09-30", description: "Mars 领导力发展项目，箭牌/宠物/食品业务。", applyUrl: "https://www.mars.com/careers", tags: ["外企", "管培"] },
  { origin: "seed", company: "雀巢", companyTier: 2, title: "2026 秋季校园招聘", category: "快消", jobType: "秋招", location: ["北京", "上海"], requirements: "应届毕业生", deadline: "2026-09-15", description: "Nestlé 市场、销售、供应链方向。", applyUrl: "https://www.nestle.com.cn/jobs", tags: ["外企", "快消"] },
  { origin: "seed", company: "百威", companyTier: 2, title: "2026 GMT 全球管培", category: "管培", jobType: "校招", location: ["上海"], requirements: "应届毕业生", deadline: "2026-09-20", description: "AB InBev 全球管培生项目，快速轮岗。", applyUrl: "https://www.budweiserapac.com/", tags: ["外企", "管培"] },
  { origin: "seed", company: "强生", companyTier: 2, title: "2026 校园招聘", category: "快消", jobType: "校招", location: ["上海", "西安"], requirements: "应届毕业生", deadline: "2026-09-25", description: "J&J 医疗、制药、消费品方向。", applyUrl: "https://www.careers.jnj.com/", tags: ["外企"] },

  // ───────────────────────── 实体 / 智能制造 ─────────────────────────
  { origin: "seed", company: "华为", companyTier: 1, title: "2026 秋季校园招聘", category: "实体", jobType: "秋招", location: ["深圳", "东莞", "北京", "上海"], requirements: "应届毕业生", deadline: "2026-09-30", description: "2012 实验室、海思、云计算、终端等研发岗位。", applyUrl: "https://career.huawei.com/", tags: ["大厂", "校招"] },
  { origin: "seed", company: "大疆", companyTier: 1, title: "2027 暑期实习", category: "实体", jobType: "暑期实习", location: ["深圳"], salary: "300-500/天", requirements: "本科及以上", deadline: "2026-11-30", description: "DJI 算法、嵌入式、机械、硬件研发实习。", applyUrl: "https://we.dji.com/", tags: ["科技", "硬件"] },
  { origin: "seed", company: "比亚迪", companyTier: 1, title: "2026 秋季校园招聘", category: "实体", jobType: "秋招", location: ["深圳", "西安", "长沙"], requirements: "应届毕业生", deadline: "2026-09-30", description: "新能源汽车、电池、半导体研发与工程岗位。", applyUrl: "https://job.byd.com/", tags: ["新能源", "校招"] },
  { origin: "seed", company: "宁德时代", companyTier: 1, title: "2026 秋招", category: "实体", jobType: "秋招", location: ["宁德", "上海"], requirements: "应届毕业生", deadline: "2026-09-25", description: "CATL 电池研发、工艺、设备方向。", applyUrl: "https://campus.catl.com/", tags: ["新能源", "校招"] },
  { origin: "seed", company: "蔚来", companyTier: 2, title: "2027 暑期实习", category: "实体", jobType: "暑期实习", location: ["上海", "合肥"], salary: "200-400/天", requirements: "本科及以上", deadline: "2026-11-15", description: "NIO 自动驾驶、三电、智能座舱实习。", applyUrl: "https://www.nio.com/careers", tags: ["新能源"] },
  { origin: "seed", company: "理想汽车", companyTier: 2, title: "2026 秋招", category: "实体", jobType: "秋招", location: ["北京"], requirements: "应届毕业生", deadline: "2026-09-18", description: "智能驾驶、智能空间、电动平台方向。", applyUrl: "https://li.auto/", tags: ["新能源", "校招"] },
  { origin: "seed", company: "中芯国际", companyTier: 2, title: "2026 秋招", category: "实体", jobType: "秋招", location: ["上海", "北京", "深圳"], requirements: "应届毕业生", deadline: "2026-09-22", description: "SMIC 半导体工艺、器件、设备方向。", applyUrl: "https://www.smics.com/", tags: ["芯片", "校招"] },
  { origin: "seed", company: "商汤科技", companyTier: 2, title: "2027 暑期实习", category: "实体", jobType: "暑期实习", location: ["上海", "深圳"], salary: "300-500/天", requirements: "本科及以上", deadline: "2026-11-20", description: "SenseTime 大模型、CV、智能驾驶研发实习。", applyUrl: "https://www.sensetime.com/cn/join-us", tags: ["AI", "科技"] },
];

export const seed: SourceAdapter = {
  id: "seed",
  label: "种子清单",
  async fetch() {
    return SEED_JOBS;
  },
};
